#!/bin/bash

if [ "$1" == "-h" ]; then
    echo -e "
Welcome to Dev Environment Setup

Usage: ./setup [-h|home_directory]
    
Options:
    -h : Show this dialogue

    home_directory : Set home directory. Defaults to \"~\".
"
    exit
fi

. .bash_config

HOME_DIR="$1"
if [ -z "$HOME_DIR" ]; then
    HOME_DIR="~/hometest"
fi

FILES_TO_REPLACE=(".bash_profile" ".bash_aliases" ".bash_ascii_art" ".bash_colors" ".bash_functions" ".vimrc" ".gitconfig")

for file in ${FILES_TO_REPLACE[@]}; do
    filePath="$HOME_DIR/$file"
    if [ -f "$filePath" ]; then
        rm "$filePath"
    fi
    cp "$file" "$filePath"
done

if [ ! -z "$GIT_USERNAME" ]; then
    git config --global user.name "$GIT_USERNAME"
fi
if [ ! -z "$GIT_EMAIL" ]; then
    git config --global user.email "$GIT_EMAIL"
fi
if [ ! -z "$GIT_EDITOR" ]; then
    git config --global core.editor "$GIT_EDITOR"
fi
